#Adding and Removing Elements in the Arrays
 np.append(h,g) -Append items to and array
 np.insert(a,1,5) -Inserts items in an array
np.delete (a,[1]) -Delete items from an array

In [1]:
import numpy as np

a = np.array([[20,40],[50,80]])
print(np.append(a,[90,100]))

[ 20  40  50  80  90 100]


In [4]:
print(np.insert(a,1,70))

[20 70 40 50 80]


In [7]:
print(np.insert(a,[1,2],[10,30], axis = 1)) #array,index,value

[[20 10 40 30]
 [50 10 80 30]]


In [11]:
print(a)
print(np.delete(a,1, axis = 1))

[[20 40]
 [50 80]]
[[20]
 [50]]
