#ADDREGATING FUNCTIONS IN NUMPY

In [11]:
import numpy as np

a = np.array([20,30,40,50])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a)) #avrage value
print(np.cumsum(a))
print(np.cumprod(a))

140
20
50
4
35.0
[ 20  50  90 140]
[     20     600   24000 1200000]


In [19]:
a = [100,500,200,250,140]
b = [10,50,30,10,40]

price = np.array(a)
quantity = np.array(b)

print(price,"\n", quantity)

print(np.cumprod([price,quantity], axis = 0))

[100 500 200 250 140] 
 [10 50 30 10 40]
[[  100   500   200   250   140]
 [ 1000 25000  6000  2500  5600]]
