#COMBINING AND SPLITTING ARRAYS

In [2]:
import numpy as np
#Concatenate

arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2])) 

[30 40 50  5  5  3]


In [3]:
print(np.concatenate([arr1,arr2],axis = 0))

[30 40 50  5  5  3]


In [5]:
print(np.vstack([arr1,arr2])) #vertical concatenate

[[30 40 50]
 [ 5  5  3]]


In [9]:
a = np.array([20,30,40,50,60,70])
b =np.array_split(a,4)
print(b)

[array([20, 30]), array([40, 50]), array([60]), array([70])]
