#SEARCH, SORT AND FILTER ARRAYS

In [3]:
import numpy as np

ar = np.array([[2,7,8,4,12,9],[2,4,8,1,3,6]])
print(np.sort(ar))

[[ 2  4  7  8  9 12]
 [ 1  2  3  4  6  8]]


In [6]:
ar = np.array([3,4,1,7,8])
s = np.where(ar % 2 == 0 )
print(s)

(array([1, 4]),)


In [8]:
ar = np.array([1,2,3,4,5])
ss = np.searchsorted(ar,5)
print(ss)

4


In [9]:
ar = np.array([20,30,40,50])

fa = [True, False, True, False]

new = ar[fa]
print(new)

[20 40]
