#Inspecting an Array
#In This we check in array what is the shape ,size,dimension and check its datatype and change
a.shape - Array dimensions
len(a) -length of array
b.ndim - number of array dimensions
e.size - number of array elements 
b.dtype - data type of array elements
b.astype(int) - convert on array to a different type

In [16]:
import numpy as np

a =([[30,40,50,60,70,10],[30,4,5,100,20,11]])
arr = np.array(a)
print(arr)
print(arr.shape) #rows,colums
print(len(arr)) #number of nested values
print(np.size(arr)) #number of elements
print(type(arr)) #datatype of variable
print(arr.dtype) #datatype of array
print(arr.astype(str)) #conversion of datatypes
print(arr.astype(int))


[[ 30  40  50  60  70  10]
 [ 30   4   5 100  20  11]]
(2, 6)
2
12
<class 'numpy.ndarray'>
int64
[['30' '40' '50' '60' '70' '10']
 ['30' '4' '5' '100' '20' '11']]
[[ 30  40  50  60  70  10]
 [ 30   4   5 100  20  11]]


#Mathematical Operations And Functions On Arrays

In [24]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [40 30]]
[[60 60]
 [40 30]]


In [25]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [  0 -10]]
[[  0  20]
 [  0 -10]]


In [26]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [400 200]]
[[900 800]
 [400 200]]


In [27]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [1.  0.5]]
[[1.  2. ]
 [1.  0.5]]


In [31]:
arr1 = np.array([[3,4],[2,5]])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[[ 9 16]
 [ 4 25]]


In [32]:
arr = np.array([9,16,25,4])
print(np.sqrt(arr1))

[[1.73205081 2.        ]
 [1.41421356 2.23606798]]
