#Numpy 1st lec

In [2]:
import numpy as np

l1 = [20,30,40]
l2 = 3
print(l1*l2)

[20, 30, 40, 20, 30, 40, 20, 30, 40]


In [4]:
a =np.array([20,30,40])
b = np.array([2])
print(a)
print(b)
print(a*b)

[20 30 40]
[2]
[40 60 80]


In [8]:
a = np.array([40,50.9,60])
print(a)

[40.  50.9 60. ]


In [11]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
arr1 = np.array([[2,3,4,5],[10,20,3,4],[50,30,40,10]])
print(arr1)

[[ 2  3  4  5]
 [10 20  3  4]
 [50 30 40 10]]


#Slicing 

In [26]:
import numpy as np
arr1 = np.array([[2,3,4,5],[10,20,3,4]])
print(arr1[0:3,2])
print(np.shape(arr1))
print(np.size(arr1))
print(np.ndim(arr1))
print(arr1.dtype)

[4 3]
(2, 4)
8
2
int64
