In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
ls=np.array([1,2,3,4,5])
ls

array([1, 2, 3, 4, 5])

*form list*

In [1]:
import numpy as np

data = [1,2,4,5]
arr_from_list = np.array(data)

print(arr_from_list)

[1 2 4 5]


*using function*

In [ ]:
np.zero

In [4]:
zero_arr = np.zeros((3, 5))
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
ones_arr = np.ones((2,6))
print(ones_arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
ones_arr[1]

array([1., 1., 1., 1., 1., 1.])

*Array andaxing and slicing*

In [17]:
arr = np.array([10,30,50,70])
first_element = arr[1]
print(first_element)

30


In [21]:
arr_2d = np.array([[1,2,3], [5,9,6]])
second_row_first_element = arr_2d[1, 2]
print(second_row_first_element)

6
